
#-- Choose build environment
virt: lxd               # LXD container
os: linux
dist: focal             # Use Ubuntu 20
language: shell


services:
  - docker


install:
  # install any dependencies required
  true

script:
  # run the build script
  - make

after_success:
